---
apiVersion: apps/v2
kind: Deployment

metadata:
  name: devops-project1

spec:
  replicas: 2

  selector:
    matchLabels:
      app: Devops-Project1

  template:
    metadata:
      labels:
        app: Devops-Project1

    spec:
      containers:
        - name: devops-project1
          image: smishra1nic/pipeline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80