---
apiVersion: v1
kind: Service

metadata:
  name: devops-project1
  labels:
    app: Devops-Project1

spec:
  selector:
    app: Devops-Project1

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31200

  type: NodePort